import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Loader2 } from 'lucide-react';
import { supabase } from '@/lib/supabase';

export function ForgotPasswordPage() {
  const [email, setEmail] = useState(''); const [loading, setLoading] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  async function submit(event: React.FormEvent) { event.preventDefault(); setLoading(true); setError(''); try { const { error: resetError } = await supabase.auth.resetPasswordForEmail(email, { redirectTo: `${window.location.origin}/reset-password` }); if (resetError) throw resetError; setMessage('If that email has an account, a password-reset link is on its way.'); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to send reset email.'); } finally { setLoading(false); } }
  return <AuthCard title="Reset your password" subtitle="Enter your email and we’ll send a secure recovery link."><form onSubmit={submit} className="space-y-6"><label className="block text-xs font-semibold uppercase tracking-[.1em] text-outline">Email<input type="email" required autoComplete="email" value={email} onChange={event => setEmail(event.target.value)} className="mt-3 w-full border-0 border-b border-outline-variant bg-transparent pb-2 text-primary outline-none focus:border-primary" /></label>{error && <p role="alert" className="text-sm text-error">{error}</p>}{message && <p role="status" className="text-sm text-emerald-700">{message}</p>}<button disabled={loading} className="flex w-full justify-center gap-2 bg-primary py-3 text-xs font-semibold uppercase tracking-[.1em] text-on-primary disabled:opacity-50">{loading && <Loader2 className="size-4 animate-spin" />}{loading ? 'Sending…' : 'Send reset link'}</button></form><p className="mt-6 text-sm text-on-surface-variant">Remembered it? <Link to="/portal/login" className="text-primary underline">Sign in</Link></p></AuthCard>;
}

export function AuthCard({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) { return <div className="min-h-screen bg-[#f7f5f0] px-6 py-8"><main className="mx-auto mt-16 w-full max-w-sm border border-[#d9b780]/35 bg-white px-7 py-8 shadow-[0_18px_50px_rgba(17,42,77,0.12)]"><Link to="/" className="mb-6 flex justify-center"><img src="/logo/fulllogo_color.png" alt="Antilia Real Estate" className="h-20 w-auto object-contain" /></Link><p className="text-center text-xs uppercase tracking-[.15em] text-[#9e7b3d]">Account recovery</p><h1 className="mt-2 text-center font-headline-lg text-primary">{title}</h1><p className="mt-3 text-center text-sm text-on-surface-variant">{subtitle}</p><div className="mt-8">{children}</div></main></div>; }
