import { Link } from 'react-router-dom';
import { Mail, MapPin, MessageCircle, Phone } from 'lucide-react';
import { getWhatsAppURL } from '@/lib/utils';

function InstagramIcon() {
  return <svg aria-hidden="true" viewBox="0 0 24 24" className="size-5 fill-none stroke-current" strokeWidth="1.8"><rect x="3.5" y="3.5" width="17" height="17" rx="5" /><circle cx="12" cy="12" r="4" /><circle cx="17.4" cy="6.7" r=".7" className="fill-current stroke-none" /></svg>;
}
function FacebookIcon() { return <span aria-hidden="true" className="font-sans text-[21px] font-bold leading-none">f</span>; }
function LinkedInIcon() { return <span aria-hidden="true" className="font-sans text-[15px] font-bold leading-none tracking-[-.08em]">in</span>; }
const socialClass = 'inline-flex size-11 items-center justify-center rounded-full border border-white/30 text-white transition-colors hover:border-[#d9b780] hover:bg-[#d9b780] hover:text-[#0b1d36] focus:outline-none focus:ring-2 focus:ring-[#d9b780] focus:ring-offset-2 focus:ring-offset-[#0b1d36]';

export function Footer() {
  const year = new Date().getFullYear();
  return <footer className="border-t border-[#d9b780]/20 bg-[#0b1d36] text-white"><div className="mx-auto grid max-w-container-max gap-10 px-margin-edge py-14 md:grid-cols-4"><div><Link to="/"><img src="/logo/fulllogo_transparent.png" alt="Antilia Real Estate" className="h-16 w-auto" /></Link><p className="mt-3 max-w-xs text-sm text-white/65">Creating Spaces, Creating Value</p><p className="mt-5 text-sm text-white/50">© {year} Antilia Real Estate</p></div><div><h2 className="mb-4 text-sm font-semibold uppercase tracking-[.12em] text-[#d9b780]">Explore</h2><nav className="space-y-2 text-sm text-white/70"><Link className="block hover:text-[#d9b780]" to="/properties?transactionType=buy">Buy</Link><Link className="block hover:text-[#d9b780]" to="/properties?transactionType=rent">Rent</Link><Link className="block hover:text-[#d9b780]" to="/about">About</Link><Link className="block hover:text-[#d9b780]" to="/contact">Contact</Link></nav></div><div><h2 className="mb-4 text-sm font-semibold uppercase tracking-[.12em] text-[#d9b780]">Contact</h2><div className="space-y-3 text-sm text-white/75"><a href="tel:+97470900064" className="flex items-center gap-2 hover:text-[#d9b780]"><Phone className="size-4" />+974 7090 0064</a><a href="tel:+97470900054" className="flex items-center gap-2 hover:text-[#d9b780]"><Phone className="size-4" />+974 7090 0054</a><a href="mailto:info@antiliarealestate.com" className="flex items-center gap-2 hover:text-[#d9b780]"><Mail className="size-4" />info@antiliarealestate.com</a><p className="flex items-start gap-2 text-white/55"><MapPin className="mt-0.5 size-4 shrink-0" />Office address pending client confirmation</p></div></div><div><h2 className="mb-4 text-sm font-semibold uppercase tracking-[.12em] text-[#d9b780]">Connect</h2><div className="flex gap-3"><a href={getWhatsAppURL()} target="_blank" rel="noopener noreferrer" aria-label="WhatsApp" title="WhatsApp" className={socialClass}><MessageCircle className="size-5" /></a><a href="#" aria-label="Instagram (link pending)" title="Instagram" className={socialClass}><InstagramIcon /></a><a href="#" aria-label="LinkedIn (link pending)" title="LinkedIn" className={socialClass}><LinkedInIcon /></a><a href="#" aria-label="Facebook (link pending)" title="Facebook" className={socialClass}><FacebookIcon /></a></div><div className="mt-6 space-y-2 text-sm text-white/65"><Link to="/privacy-policy" className="block hover:text-[#d9b780]">Privacy Policy</Link><Link to="/terms-and-conditions" className="block hover:text-[#d9b780]">Terms and Conditions</Link></div></div></div></footer>;
}
