INSERT INTO properties (
  slug,
  title,
  description,
  category,
  type,
  price,
  price_period,
  currency,
  location,
  area,
  bedrooms,
  bathrooms,
  area_sqft,
  furnishing,
  status,
  featured,
  amenities,
  images,
  seo_title,
  seo_description,
  listing_status
)
VALUES (
  'premium-furnished-2bhk-matar-qadeem',
  'Premium Furnished 2BHK Apartment',
  'Premium fully furnished two-bedroom apartment for rent in Matar Qadeem, Old Airport Area. Includes large closets, a kitchen, bathroom, central air conditioning, elevator access, and a rooftop pool. Water and electricity are included. Internet is not included. Available on an annual contract with one month free. Monthly variants: QAR 6,900, QAR 7,000, and QAR 7,300.',
  'rent',
  'apartment',
  6900,
  'per month',
  'QAR',
  'Old Airport Area, Doha, Qatar',
  'Matar Qadeem',
  2,
  1,
  0,
  'furnished',
  'available',
  true,
  ARRAY[
    'Fully furnished',
    'Two bedrooms',
    'Large closets',
    'Kitchen',
    'Bathroom',
    'Central AC',
    'Elevator',
    'Rooftop pool',
    'Water and electricity included',
    'Annual contract with one month free'
  ],
  jsonb_build_array(
    jsonb_build_object('url', '/Properties/property%201/WhatsApp%20Image%202026-07-22%20at%209.33.18%20PM.jpeg', 'alt', 'Premium furnished 2BHK apartment interior', 'order', 0, 'is_primary', true),
    jsonb_build_object('url', '/Properties/property%201/WhatsApp%20Image%202026-07-22%20at%209.33.19%20PM.jpeg', 'alt', 'Premium furnished 2BHK apartment living area', 'order', 1, 'is_primary', false),
    jsonb_build_object('url', '/Properties/property%201/WhatsApp%20Image%202026-07-22%20at%209.33.20%20PM.jpeg', 'alt', 'Premium furnished 2BHK apartment bedroom', 'order', 2, 'is_primary', false),
    jsonb_build_object('url', '/Properties/property%201/WhatsApp%20Image%202026-07-22%20at%209.33.21%20PM.jpeg', 'alt', 'Premium furnished 2BHK apartment kitchen', 'order', 3, 'is_primary', false),
    jsonb_build_object('url', '/Properties/property%201/WhatsApp%20Image%202026-07-22%20at%209.33.22%20PM.jpeg', 'alt', 'Premium furnished 2BHK apartment amenity', 'order', 4, 'is_primary', false)
  ),
  'Premium Furnished 2BHK Apartment for Rent in Matar Qadeem',
  'Fully furnished 2BHK apartment in Matar Qadeem with central AC, rooftop pool, and one month free on an annual contract.',
  'approved'
)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  type = EXCLUDED.type,
  price = EXCLUDED.price,
  price_period = EXCLUDED.price_period,
  currency = EXCLUDED.currency,
  location = EXCLUDED.location,
  area = EXCLUDED.area,
  bedrooms = EXCLUDED.bedrooms,
  bathrooms = EXCLUDED.bathrooms,
  area_sqft = EXCLUDED.area_sqft,
  furnishing = EXCLUDED.furnishing,
  status = EXCLUDED.status,
  featured = EXCLUDED.featured,
  amenities = EXCLUDED.amenities,
  images = EXCLUDED.images,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  listing_status = EXCLUDED.listing_status;
